<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BrandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Populates the brands table with initial data.
     */
    public function run()
    {
        DB::table('brands')->insert([
            [
                'id' => 29,
                'name' => 'Microsoft',
                'slug' => 'microsoft',
                'position' => 1,
                'image' => '1745234672.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'created_at' => '2024-06-26 19:19:24',
                'updated_at' => '2025-06-30 17:22:04'
            ],
            [
                'id' => 30,
                'name' => 'Dell',
                'slug' => 'dell',
                'position' => 2,
                'image' => '1745234682.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'created_at' => '2024-06-26 20:00:26',
                'updated_at' => '2025-05-08 09:23:39'
            ],
            [
                'id' => 31,
                'name' => 'SAMSUNG',
                'slug' => 'samsung',
                'position' => 3,
                'image' => '1745234699.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'created_at' => '2024-06-26 20:01:03',
                'updated_at' => '2025-05-08 09:23:44'
            ],
            [
                'id' => 32,
                'name' => 'HP',
                'slug' => 'hp',
                'position' => 4,
                'image' => '1745234709.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'created_at' => '2024-06-26 20:01:22',
                'updated_at' => '2025-06-06 14:51:10'
            ],
            [
                'id' => 33,
                'name' => 'Lenovo',
                'slug' => 'lenovo',
                'position' => 5,
                'image' => '1745234719.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'created_at' => '2024-06-26 20:01:37',
                'updated_at' => '2025-05-08 09:23:53'
            ],
            [
                'id' => 34,
                'name' => 'ASUS',
                'slug' => 'asus',
                'position' => 6,
                'image' => '1745234746.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'created_at' => '2024-06-26 20:02:00',
                'updated_at' => '2025-06-10 17:57:12'
            ],
            [
                'id' => 35,
                'name' => 'WALTON',
                'slug' => 'walton',
                'position' => 7,
                'image' => '1745234756.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'created_at' => '2024-06-26 20:02:22',
                'updated_at' => '2025-05-08 09:24:14'
            ],
            [
                'id' => 36,
                'name' => 'Acer',
                'slug' => 'acer',
                'position' => 8,
                'image' => '1745234765.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'created_at' => '2024-06-26 20:02:45',
                'updated_at' => '2025-06-13 17:25:59'
            ],
            [
                'id' => 37,
                'name' => 'Apple',
                'slug' => 'apple',
                'position' => 9,
                'image' => '1745234776.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'created_at' => '2024-06-26 20:03:21',
                'updated_at' => '2025-06-17 17:41:06'
            ],
            [
                'id' => 39,
                'name' => 'SONY',
                'slug' => 'sony',
                'position' => 11,
                'image' => '1745234797.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'created_at' => '2024-06-26 20:03:48',
                'updated_at' => '2025-05-08 09:24:34'
            ],
            [
                'id' => 40,
                'name' => 'Adata',
                'slug' => 'adata',
                'position' => 12,
                'image' => '1745234811.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'created_at' => '2024-06-26 20:04:13',
                'updated_at' => '2025-05-08 09:24:41'
            ],
            [
                'id' => 41,
                'name' => 'Intel',
                'slug' => 'intel',
                'position' => 13,
                'image' => '1745234826.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'created_at' => '2024-06-26 20:04:35',
                'updated_at' => '2025-05-08 09:24:48'
            ],
            [
                'id' => 42,
                'name' => 'Gigabyte',
                'slug' => 'gigabyte',
                'position' => 14,
                'image' => '1745234837.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'created_at' => '2024-07-04 10:37:22',
                'updated_at' => '2025-05-08 09:24:55'
            ],
            [
                'id' => 46,
                'name' => 'MSI',
                'slug' => 'msi',
                'position' => 18,
                'image' => '1745234867.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'created_at' => '2024-07-07 10:53:04',
                'updated_at' => '2025-06-06 10:00:26'
            ],
            [
                'id' => 58,
                'name' => 'Logitech',
                'slug' => 'logitech',
                'position' => 15,
                'image' => '1745234848.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'created_at' => '2025-04-21 08:27:44',
                'updated_at' => '2025-05-08 09:25:01'
            ],
            [
                'id' => 59,
                'name' => 'A4tech',
                'slug' => 'a4tech',
                'position' => 16,
                'image' => '1745234858.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'created_at' => '2025-04-21 08:28:19',
                'updated_at' => '2025-05-08 09:25:08'
            ],
            [
                'id' => 60,
                'name' => 'Epson',
                'slug' => 'epson',
                'position' => null,
                'image' => '1745227068.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-04-21 09:17:48',
                'updated_at' => '2025-06-01 05:35:55'
            ],
            [
                'id' => 61,
                'name' => 'Aiwa',
                'slug' => 'aiwa',
                'position' => null,
                'image' => '1748156916.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-05-25 07:08:36',
                'updated_at' => '2025-06-01 05:36:03'
            ],
            [
                'id' => 62,
                'name' => 'Apacer',
                'slug' => 'apacer',
                'position' => null,
                'image' => '1748168586.jpeg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-05-25 10:23:06',
                'updated_at' => '2025-06-01 05:36:11'
            ],
            [
                'id' => 63,
                'name' => 'HAVIT',
                'slug' => 'havit',
                'position' => null,
                'image' => '1748254144.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-05-26 10:09:04',
                'updated_at' => '2025-06-01 05:36:20'
            ],
            [
                'id' => 64,
                'name' => 'T-WOLF',
                'slug' => 't-wolf',
                'position' => null,
                'image' => '1748345445.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-05-27 11:30:45',
                'updated_at' => '2025-06-01 05:36:28'
            ],
            [
                'id' => 65,
                'name' => 'Fantech',
                'slug' => 'fantech',
                'position' => null,
                'image' => '1748414312.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-05-28 06:38:32',
                'updated_at' => '2025-06-01 05:36:37'
            ],
            [
                'id' => 66,
                'name' => 'Rapoo',
                'slug' => 'rapoo',
                'position' => null,
                'image' => '1748415256.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-05-28 06:54:16',
                'updated_at' => '2025-06-01 05:36:45'
            ],
            [
                'id' => 67,
                'name' => 'Tenda',
                'slug' => 'tenda',
                'position' => null,
                'image' => '1748416088.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-05-28 07:08:08',
                'updated_at' => '2025-06-01 05:36:55'
            ],
            [
                'id' => 68,
                'name' => 'Smart',
                'slug' => 'smart',
                'position' => null,
                'image' => '1748419793.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-05-28 08:08:46',
                'updated_at' => '2025-06-01 05:37:03'
            ],
            [
                'id' => 69,
                'name' => 'Solitine',
                'slug' => 'solitine',
                'position' => null,
                'image' => '1748424832.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-05-28 09:33:52',
                'updated_at' => '2025-06-01 05:37:12'
            ],
            [
                'id' => 70,
                'name' => 'Twinmos',
                'slug' => 'twinmos',
                'position' => null,
                'image' => '1748507267.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-05-29 08:27:47',
                'updated_at' => '2025-06-01 05:37:29'
            ],
            [
                'id' => 71,
                'name' => 'Value Top',
                'slug' => 'value-top',
                'position' => null,
                'image' => '1748852367.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-06-02 08:19:27',
                'updated_at' => '2025-06-12 08:42:14'
            ],
            [
                'id' => 72,
                'name' => 'MaxGreen',
                'slug' => 'maxgreen',
                'position' => null,
                'image' => '1749630127.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-06-11 08:22:07',
                'updated_at' => '2025-06-11 08:22:07'
            ],
            [
                'id' => 73,
                'name' => 'Xiaomi',
                'slug' => 'xiaomi',
                'position' => null,
                'image' => '1749631514.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-06-11 08:45:15',
                'updated_at' => '2025-06-11 08:45:15'
            ],
            [
                'id' => 74,
                'name' => 'Non Brand',
                'slug' => 'non-brand',
                'position' => null,
                'image' => '1749634170.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-06-11 09:20:10',
                'updated_at' => '2025-06-11 09:29:30'
            ],
            [
                'id' => 75,
                'name' => 'Orico',
                'slug' => 'orico',
                'position' => null,
                'image' => '1749634365.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-06-11 09:32:45',
                'updated_at' => '2025-06-11 09:32:45'
            ],
            [
                'id' => 76,
                'name' => 'DeepCool',
                'slug' => 'deepcool',
                'position' => null,
                'image' => '1749662116.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-06-11 17:15:16',
                'updated_at' => '2025-06-11 17:15:16'
            ],
            [
                'id' => 77,
                'name' => 'Black Cat',
                'slug' => 'black-cat',
                'position' => null,
                'image' => '1749662426.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-06-11 17:20:26',
                'updated_at' => '2025-06-11 17:20:26'
            ],
            [
                'id' => 78,
                'name' => 'AMD',
                'slug' => 'amd',
                'position' => null,
                'image' => '1749751513.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-06-12 18:05:13',
                'updated_at' => '2025-06-12 18:05:13'
            ],
            [
                'id' => 79,
                'name' => 'Zotac',
                'slug' => 'zotac',
                'position' => null,
                'image' => '1750096259.webp',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-06-16 17:50:59',
                'updated_at' => '2025-06-16 17:50:59'
            ],
            [
                'id' => 80,
                'name' => 'Western Digital',
                'slug' => 'western-digital',
                'position' => null,
                'image' => '1750763783.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-06-24 11:16:23',
                'updated_at' => '2025-06-28 16:32:08'
            ],
            [
                'id' => 81,
                'name' => 'King Super',
                'slug' => 'king-super',
                'position' => null,
                'image' => '1750855262.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-06-25 12:40:10',
                'updated_at' => '2025-06-28 16:32:20'
            ],
            [
                'id' => 82,
                'name' => 'Kingston',
                'slug' => 'kingston',
                'position' => null,
                'image' => '1751967679.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-08 09:41:19',
                'updated_at' => '2025-07-09 11:51:30'
            ],
            [
                'id' => 83,
                'name' => 'Kstar',
                'slug' => 'kstar',
                'position' => null,
                'image' => '1752043886.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-09 06:51:26',
                'updated_at' => '2025-07-09 12:03:48'
            ],
            [
                'id' => 84,
                'name' => 'Atlas',
                'slug' => 'atlas',
                'position' => null,
                'image' => '1752054212.jpeg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-09 09:43:32',
                'updated_at' => '2025-07-09 12:04:05'
            ],
            [
                'id' => 85,
                'name' => 'Dahua',
                'slug' => 'dahua',
                'position' => null,
                'image' => '1752057664.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-09 10:41:04',
                'updated_at' => '2025-07-09 12:04:16'
            ],
            [
                'id' => 86,
                'name' => 'Optoma',
                'slug' => 'optoma',
                'position' => null,
                'image' => '1752058081.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-09 10:48:01',
                'updated_at' => '2025-07-09 10:48:01'
            ],
            [
                'id' => 87,
                'name' => 'HikVision',
                'slug' => 'hikvision',
                'position' => null,
                'image' => '1752060839.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-09 11:34:00',
                'updated_at' => '2025-07-09 12:04:40'
            ],
            [
                'id' => 88,
                'name' => 'BenQ',
                'slug' => 'benq',
                'position' => null,
                'image' => '1752064318.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-09 12:31:58',
                'updated_at' => '2025-07-09 12:31:58'
            ],
            [
                'id' => 89,
                'name' => 'TOA',
                'slug' => 'toa',
                'position' => null,
                'image' => '1752138275.jpeg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-10 09:04:35',
                'updated_at' => '2025-07-10 09:04:35'
            ],
            [
                'id' => 90,
                'name' => 'Esonic',
                'slug' => 'esonic',
                'position' => null,
                'image' => '1752151892.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-10 12:51:32',
                'updated_at' => '2025-07-11 09:00:46'
            ],
            [
                'id' => 91,
                'name' => 'Hi-Power',
                'slug' => 'hi-power',
                'position' => null,
                'image' => '1752308828.jpeg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-12 08:27:08',
                'updated_at' => '2025-07-12 08:43:19'
            ],
            [
                'id' => 92,
                'name' => 'Bingji',
                'slug' => 'bingji',
                'position' => null,
                'image' => '1752383975.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-12 12:38:08',
                'updated_at' => '2025-07-13 05:19:35'
            ],
            [
                'id' => 93,
                'name' => 'Tp-Link',
                'slug' => 'tp-link',
                'position' => null,
                'image' => '1752391104.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-13 07:18:24',
                'updated_at' => '2025-07-13 07:18:24'
            ],
            [
                'id' => 94,
                'name' => 'IMOU',
                'slug' => 'imou',
                'position' => null,
                'image' => '1752565110.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-15 07:38:30',
                'updated_at' => '2025-07-15 07:38:30'
            ],
            [
                'id' => 95,
                'name' => 'ViewSonic',
                'slug' => 'viewsonic',
                'position' => null,
                'image' => '1752597496.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-15 16:38:16',
                'updated_at' => '2025-07-15 16:38:16'
            ],
            [
                'id' => 96,
                'name' => 'VIVITEK',
                'slug' => 'vivitek',
                'position' => null,
                'image' => '1752655517.jpeg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-16 08:45:17',
                'updated_at' => '2025-07-16 08:45:17'
            ],
            [
                'id' => 97,
                'name' => 'Boxlight',
                'slug' => 'boxlight',
                'position' => null,
                'image' => '1752685514.webp',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-16 17:05:14',
                'updated_at' => '2025-07-16 17:05:14'
            ],
            [
                'id' => 98,
                'name' => 'AUN',
                'slug' => 'aun',
                'position' => null,
                'image' => '1752753427.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-17 11:57:07',
                'updated_at' => '2025-07-17 11:57:07'
            ],
            [
                'id' => 99,
                'name' => 'InFocus',
                'slug' => 'infocus',
                'position' => null,
                'image' => '1752755621.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-17 12:33:41',
                'updated_at' => '2025-07-17 12:33:41'
            ],
            [
                'id' => 100,
                'name' => 'Cheerlux',
                'slug' => 'cheerlux',
                'position' => null,
                'image' => '1752757348.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-17 13:02:28',
                'updated_at' => '2025-07-17 13:02:28'
            ],
            [
                'id' => 101,
                'name' => 'Philips',
                'slug' => 'philips',
                'position' => null,
                'image' => '1752902122.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-19 05:15:22',
                'updated_at' => '2025-07-19 05:15:22'
            ],
            [
                'id' => 102,
                'name' => 'XINJI',
                'slug' => 'xinji',
                'position' => null,
                'image' => '1752913489.webp',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-19 08:24:49',
                'updated_at' => '2025-07-19 08:24:49'
            ],
            [
                'id' => 103,
                'name' => 'Blisbond',
                'slug' => 'blisbond',
                'position' => null,
                'image' => '1752914941.webp',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-19 08:49:01',
                'updated_at' => '2025-07-19 08:49:01'
            ],
            [
                'id' => 104,
                'name' => 'Microlab',
                'slug' => 'microlab',
                'position' => null,
                'image' => '1752924131.jpeg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-19 11:22:11',
                'updated_at' => '2025-07-19 11:22:11'
            ],
            [
                'id' => 105,
                'name' => 'Dopah',
                'slug' => 'dopah',
                'position' => null,
                'image' => '1752924540.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-19 11:29:00',
                'updated_at' => '2025-07-19 11:29:00'
            ],
            [
                'id' => 106,
                'name' => 'APOLLO',
                'slug' => 'apollo',
                'position' => null,
                'image' => '1757591360.jpeg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-19 11:50:44',
                'updated_at' => '2025-09-11 11:49:20'
            ],
            [
                'id' => 107,
                'name' => 'HTDZ',
                'slug' => 'htdz',
                'position' => null,
                'image' => '1752993382.webp',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-20 06:36:22',
                'updated_at' => '2025-07-20 06:36:22'
            ],
            [
                'id' => 109,
                'name' => 'Jabra',
                'slug' => 'jabra',
                'position' => null,
                'image' => '1753004940.webp',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-20 09:49:00',
                'updated_at' => '2025-07-20 09:49:00'
            ],
            [
                'id' => 110,
                'name' => 'CMX',
                'slug' => 'cmx',
                'position' => null,
                'image' => '1753082041.jpeg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-21 07:14:01',
                'updated_at' => '2025-07-21 07:14:01'
            ],
            [
                'id' => 111,
                'name' => 'TEV',
                'slug' => 'tev',
                'position' => null,
                'image' => '1753101324.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-21 12:35:24',
                'updated_at' => '2025-07-21 12:35:24'
            ],
            [
                'id' => 112,
                'name' => 'AVerMedia',
                'slug' => 'avermedia',
                'position' => null,
                'image' => '1753102894.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-21 13:01:34',
                'updated_at' => '2025-07-21 13:01:34'
            ],
            [
                'id' => 113,
                'name' => 'Poly',
                'slug' => 'poly',
                'position' => null,
                'image' => '1753164541.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-22 06:09:01',
                'updated_at' => '2025-07-22 06:09:01'
            ],
            [
                'id' => 114,
                'name' => 'AVer',
                'slug' => 'aver',
                'position' => null,
                'image' => '1753166090.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-22 06:34:50',
                'updated_at' => '2025-07-22 06:34:50'
            ],
            [
                'id' => 115,
                'name' => 'Grandstream',
                'slug' => 'grandstream',
                'position' => null,
                'image' => '1753167949.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-22 07:05:49',
                'updated_at' => '2025-07-22 07:05:49'
            ],
            [
                'id' => 116,
                'name' => 'ScreenBeam',
                'slug' => 'screenbeam',
                'position' => null,
                'image' => '1753180778.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-22 10:39:38',
                'updated_at' => '2025-07-22 10:39:38'
            ],
            [
                'id' => 117,
                'name' => 'MAXHUB',
                'slug' => 'maxhub',
                'position' => null,
                'image' => '1753184339.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-22 11:38:59',
                'updated_at' => '2025-07-22 11:38:59'
            ],
            [
                'id' => 119,
                'name' => 'Tiandy',
                'slug' => 'tiandy',
                'position' => null,
                'image' => '1753252013.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-23 06:26:53',
                'updated_at' => '2025-07-23 06:26:53'
            ],
            [
                'id' => 120,
                'name' => 'JBL',
                'slug' => 'jbl',
                'position' => null,
                'image' => '1753339606.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-24 06:46:47',
                'updated_at' => '2025-07-24 06:46:47'
            ],
            [
                'id' => 121,
                'name' => 'LG',
                'slug' => 'lg',
                'position' => null,
                'image' => '1753520595.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-26 09:03:15',
                'updated_at' => '2025-07-26 09:03:15'
            ],
            [
                'id' => 122,
                'name' => 'Hitachi',
                'slug' => 'hitachi',
                'position' => null,
                'image' => '1753595727.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-27 05:55:27',
                'updated_at' => '2025-07-27 05:55:27'
            ],
            [
                'id' => 123,
                'name' => 'METZ',
                'slug' => 'metz',
                'position' => null,
                'image' => '1753599109.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-27 06:51:49',
                'updated_at' => '2025-07-27 06:51:49'
            ],
            [
                'id' => 124,
                'name' => 'ARMOR',
                'slug' => 'armor',
                'position' => null,
                'image' => '1753609958.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-27 09:52:38',
                'updated_at' => '2025-07-27 09:52:38'
            ],
            [
                'id' => 125,
                'name' => 'Panasonic',
                'slug' => 'panasonic',
                'position' => null,
                'image' => '1753639022.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-27 17:57:02',
                'updated_at' => '2025-07-27 17:57:02'
            ],
            [
                'id' => 126,
                'name' => 'BDCOM',
                'slug' => 'bdcom',
                'position' => null,
                'image' => '1753677615.webp',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-28 04:40:16',
                'updated_at' => '2025-07-28 04:40:16'
            ],
            [
                'id' => 127,
                'name' => 'ZKTeco',
                'slug' => 'zkteco',
                'position' => null,
                'image' => '1753791431.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-29 12:17:11',
                'updated_at' => '2025-07-29 12:17:11'
            ],
            [
                'id' => 128,
                'name' => 'Newline',
                'slug' => 'newline',
                'position' => null,
                'image' => '1753791657.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-29 12:20:57',
                'updated_at' => '2025-07-29 12:20:57'
            ],
            [
                'id' => 129,
                'name' => 'iBoard',
                'slug' => 'iboard',
                'position' => null,
                'image' => '1753791748.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-29 12:22:28',
                'updated_at' => '2025-07-29 12:22:28'
            ],
            [
                'id' => 130,
                'name' => 'Innovtech',
                'slug' => 'innovtech',
                'position' => null,
                'image' => '1753979630.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-07-31 16:33:50',
                'updated_at' => '2025-07-31 16:33:50'
            ],
            [
                'id' => 131,
                'name' => 'Pantum',
                'slug' => 'pantum',
                'position' => null,
                'image' => '1754113746.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-02 05:49:06',
                'updated_at' => '2025-08-02 05:49:06'
            ],
            [
                'id' => 132,
                'name' => 'Brother',
                'slug' => 'brother',
                'position' => null,
                'image' => '1754119199.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-02 07:19:59',
                'updated_at' => '2025-08-02 07:19:59'
            ],
            [
                'id' => 133,
                'name' => 'Canon',
                'slug' => 'canon',
                'position' => null,
                'image' => '1754136166.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-02 12:02:46',
                'updated_at' => '2025-08-02 12:02:46'
            ],
            [
                'id' => 134,
                'name' => 'Fujifilm',
                'slug' => 'fujifilm',
                'position' => null,
                'image' => '1754297720.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-04 08:55:20',
                'updated_at' => '2025-08-04 08:55:20'
            ],
            [
                'id' => 135,
                'name' => 'Zebra',
                'slug' => 'zebra',
                'position' => null,
                'image' => '1754380201.jpg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-05 07:50:01',
                'updated_at' => '2025-08-05 07:50:01'
            ],
            [
                'id' => 136,
                'name' => 'Evolis',
                'slug' => 'evolis',
                'position' => null,
                'image' => '1754381186.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-05 08:06:26',
                'updated_at' => '2025-08-05 08:06:26'
            ],
            [
                'id' => 137,
                'name' => 'HID',
                'slug' => 'hid',
                'position' => null,
                'image' => '1754386379.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-05 09:32:59',
                'updated_at' => '2025-08-05 09:32:59'
            ],
            [
                'id' => 138,
                'name' => 'Deli',
                'slug' => 'deli',
                'position' => null,
                'image' => '1754387252.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-05 09:47:32',
                'updated_at' => '2025-08-05 09:47:32'
            ],
            [
                'id' => 139,
                'name' => 'RONGTA',
                'slug' => 'rongta',
                'position' => null,
                'image' => '1754389331.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-05 10:22:11',
                'updated_at' => '2025-08-05 10:22:11'
            ],
            [
                'id' => 140,
                'name' => 'Sewoo',
                'slug' => 'sewoo',
                'position' => null,
                'image' => '1754460928.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-06 06:15:28',
                'updated_at' => '2025-08-06 06:15:28'
            ],
            [
                'id' => 141,
                'name' => 'Xprinter',
                'slug' => 'xprinter',
                'position' => null,
                'image' => '1754464021.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-06 07:07:01',
                'updated_at' => '2025-08-06 07:07:01'
            ],
            [
                'id' => 142,
                'name' => 'SPRT',
                'slug' => 'sprt',
                'position' => null,
                'image' => '1754475705.jpeg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-06 10:21:45',
                'updated_at' => '2025-08-06 10:21:45'
            ],
            [
                'id' => 143,
                'name' => 'Sunmi',
                'slug' => 'sunmi',
                'position' => null,
                'image' => '1754498510.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-06 16:41:50',
                'updated_at' => '2025-08-06 16:41:50'
            ],
            [
                'id' => 144,
                'name' => 'Citizen',
                'slug' => 'citizen',
                'position' => null,
                'image' => '1754498687.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-06 16:44:47',
                'updated_at' => '2025-08-06 16:44:47'
            ],
            [
                'id' => 145,
                'name' => 'G-Printer',
                'slug' => 'g-printer',
                'position' => null,
                'image' => '1754498815.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-06 16:46:55',
                'updated_at' => '2025-08-06 16:46:55'
            ]
        ]);

        DB::table('brands')->insert([
            [
                'id' => 146,
                'name' => 'Bixolon',
                'slug' => 'bixolon',
                'position' => null,
                'image' => '1754499052.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-06 16:50:52',
                'updated_at' => '2025-08-06 16:50:52'
            ],
            [
                'id' => 147,
                'name' => 'TSC',
                'slug' => 'tsc',
                'position' => null,
                'image' => '1754829427.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-10 12:37:07',
                'updated_at' => '2025-08-10 12:37:07'
            ],
            [
                'id' => 148,
                'name' => 'GoDEX',
                'slug' => 'godex',
                'position' => null,
                'image' => '1754899463.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-11 08:04:23',
                'updated_at' => '2025-08-11 08:04:23'
            ],
            [
                'id' => 149,
                'name' => 'Toshiba',
                'slug' => 'toshiba',
                'position' => null,
                'image' => '1754906262.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-11 09:57:42',
                'updated_at' => '2025-08-11 09:57:42'
            ],
            [
                'id' => 150,
                'name' => 'Sharp',
                'slug' => 'sharp',
                'position' => null,
                'image' => '1755756313.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-12 08:25:41',
                'updated_at' => '2025-08-21 06:05:13'
            ],
            [
                'id' => 151,
                'name' => 'Ricoh',
                'slug' => 'ricoh',
                'position' => null,
                'image' => '1755070061.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-13 07:27:41',
                'updated_at' => '2025-08-13 07:27:41'
            ],
            [
                'id' => 152,
                'name' => 'Power Print',
                'slug' => 'power-print',
                'position' => null,
                'image' => '1755413412.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-17 06:32:08',
                'updated_at' => '2025-08-17 06:50:12'
            ],
            [
                'id' => 153,
                'name' => 'True Trust',
                'slug' => 'true-trust',
                'position' => null,
                'image' => '1755418084.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-17 08:08:04',
                'updated_at' => '2025-08-17 08:08:04'
            ],
            [
                'id' => 154,
                'name' => 'Starink',
                'slug' => 'starink',
                'position' => null,
                'image' => '1755495953.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-18 05:45:53',
                'updated_at' => '2025-08-18 05:45:53'
            ],
            [
                'id' => 155,
                'name' => 'G&G',
                'slug' => 'gg',
                'position' => null,
                'image' => '1755680410.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-20 08:31:26',
                'updated_at' => '2025-08-20 09:00:10'
            ],
            [
                'id' => 156,
                'name' => 'Print-Rite',
                'slug' => 'print-rite',
                'position' => null,
                'image' => '1755709173.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-20 16:59:33',
                'updated_at' => '2025-08-20 16:59:33'
            ],
            [
                'id' => 157,
                'name' => 'LongPrint',
                'slug' => 'longprint',
                'position' => null,
                'image' => '1755928845.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-23 06:00:45',
                'updated_at' => '2025-08-23 06:00:45'
            ],
            [
                'id' => 158,
                'name' => 'SafeWay',
                'slug' => 'safeway',
                'position' => null,
                'image' => '1755967659.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-08-23 16:47:39',
                'updated_at' => '2025-08-23 16:47:39'
            ],
            [
                'id' => 159,
                'name' => 'Plustek',
                'slug' => 'plustek',
                'position' => null,
                'image' => '1756887394.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-03 08:16:34',
                'updated_at' => '2025-09-03 08:16:34'
            ],
            [
                'id' => 160,
                'name' => 'Avision',
                'slug' => 'avision',
                'position' => null,
                'image' => '1756889381.jpeg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-03 08:49:41',
                'updated_at' => '2025-09-03 08:49:41'
            ],
            [
                'id' => 161,
                'name' => 'Fujitsu',
                'slug' => 'fujitsu',
                'position' => null,
                'image' => '1756890572.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-03 09:09:32',
                'updated_at' => '2025-09-03 09:09:32'
            ],
            [
                'id' => 162,
                'name' => 'Kodak',
                'slug' => 'kodak',
                'position' => null,
                'image' => '1756901932.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-03 12:18:52',
                'updated_at' => '2025-09-03 12:18:52'
            ],
            [
                'id' => 163,
                'name' => 'Winson',
                'slug' => 'winson',
                'position' => null,
                'image' => '1756978088.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-04 09:28:08',
                'updated_at' => '2025-09-04 09:28:08'
            ],
            [
                'id' => 164,
                'name' => 'Yumite',
                'slug' => 'yumite',
                'position' => null,
                'image' => '1757139673.jpeg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-06 06:21:13',
                'updated_at' => '2025-09-06 06:21:13'
            ],
            [
                'id' => 165,
                'name' => 'ZEBEX',
                'slug' => 'zebex',
                'position' => null,
                'image' => '1757146797.jpeg',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-06 08:19:57',
                'updated_at' => '2025-09-06 08:19:57'
            ],
            [
                'id' => 166,
                'name' => 'Honeywell',
                'slug' => 'honeywell',
                'position' => null,
                'image' => '1757150156.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-06 09:15:56',
                'updated_at' => '2025-09-06 09:15:56'
            ],
            [
                'id' => 167,
                'name' => 'Sunlux',
                'slug' => 'sunlux',
                'position' => null,
                'image' => '1757226647.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-07 06:30:47',
                'updated_at' => '2025-09-07 06:30:47'
            ],
            [
                'id' => 168,
                'name' => 'Maken',
                'slug' => 'maken',
                'position' => null,
                'image' => '1757246547.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-07 12:02:27',
                'updated_at' => '2025-09-07 12:02:27'
            ],
            [
                'id' => 169,
                'name' => 'Hellotel',
                'slug' => 'hellotel',
                'position' => null,
                'image' => '1757250033.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-07 13:00:33',
                'updated_at' => '2025-09-07 13:00:33'
            ],
            [
                'id' => 170,
                'name' => 'Mitel',
                'slug' => 'mitel',
                'position' => null,
                'image' => '1757330506.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-08 11:21:46',
                'updated_at' => '2025-09-08 11:21:46'
            ],
            [
                'id' => 171,
                'name' => 'Cisco',
                'slug' => 'cisco',
                'position' => null,
                'image' => '1757403669.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-09 07:41:09',
                'updated_at' => '2025-09-09 07:41:09'
            ],
            [
                'id' => 172,
                'name' => 'Avaya',
                'slug' => 'avaya',
                'position' => null,
                'image' => '1757404685.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-09 07:58:05',
                'updated_at' => '2025-09-09 07:58:05'
            ],
            [
                'id' => 173,
                'name' => 'DINSTAR',
                'slug' => 'dinstar',
                'position' => null,
                'image' => '1757405473.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-09 08:11:13',
                'updated_at' => '2025-09-09 08:11:13'
            ],
            [
                'id' => 174,
                'name' => 'Snom',
                'slug' => 'snom',
                'position' => null,
                'image' => '1757418370.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-09 11:46:10',
                'updated_at' => '2025-09-09 11:46:10'
            ],
            [
                'id' => 175,
                'name' => 'Flyingvoice',
                'slug' => 'flyingvoice',
                'position' => null,
                'image' => '1757422668.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-09 12:57:48',
                'updated_at' => '2025-09-09 12:57:48'
            ],
            [
                'id' => 176,
                'name' => 'Zycoo',
                'slug' => 'zycoo',
                'position' => null,
                'image' => '1757584305.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-11 09:51:45',
                'updated_at' => '2025-09-11 09:51:45'
            ],
            [
                'id' => 177,
                'name' => 'Kington',
                'slug' => 'kington',
                'position' => null,
                'image' => '1757592738.png',
                'description' => null,
                'meta_title' => null,
                'meta_image' => null,
                'meta_description' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-11 12:11:26',
                'updated_at' => '2025-09-11 12:12:18'
            ]
        ]);
    }
}
