<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class ColorImage extends Model
{

    protected $table = 'color_images';

    protected $fillable = [
        'product_id',
        'color_attribute_id',
        'image',
    ];

    // Relationships
    // public function colors(): BelongsToMany
    // {
    //     return $this->belongsToMany(Color::class, 'color_images');
    // }

    // Relationships generated by models:generate-relationships command
    public function product()
    {
        return $this->belongsTo(Product::class, 'product_id');
    }

    public function colorAttribute()
    {
        return $this->belongsTo(ColorAttribute::class, 'color_attribute_id');
    }
}
