<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class ColorAttribute extends Model
{
    use HasFactory;

    protected $table = 'color_attributes';

    protected $fillable = [
        // Add your fillable fields here
    ];

    protected $casts = [
        // Add your casts here
    ];

    // Relationships
    // public function colors(): BelongsToMany
    // {
    //     return $this->belongsToMany(Color::class, 'color_attributes');
    // }

    // Relationships generated by models:generate-relationships command
    public function colorImages()
    {
        return $this->hasMany(ColorImage::class, 'color_attribute_id');
    }
}
