<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MultiImage extends Model
{
    use HasFactory;

    protected $table = 'multi_images';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'product_id',
        'photo',
        'created_at',
    ];

    // Relationships generated by models:generate-relationships command
    public function product()
    {
        return $this->belongsTo(Product::class, 'product_id');
    }
}