<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class ProductCart extends Model
{

    protected $table = 'product_carts';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id',
        'product_id',
        'qty',
        'price',
        'color',
        'size',
        'variation',
        'cartTotal',
    ];

    public function products(): BelongsToMany
    {
        return $this->belongsToMany(Product::class, 'product_carts');
    }

    // Relationships generated by models:generate-relationships command
    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function product()
    {
        return $this->belongsTo(Product::class, 'product_id');
    }
}
