<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Upazilla extends Model
{
    use HasFactory;

    protected $table = 'upazillas';

    protected $fillable = [
        // Add your fillable fields here
    ];

    protected $casts = [
        // Add your casts here
    ];

    public function userAddresses(): HasMany
    {
        return $this->hasMany(UserAddress::class, 'upazilla_id');
    }

    // Relationships generated by models:generate-relationships command
    public function orders()
    {
        return $this->hasMany(Order::class, 'upazilla_id');
    }
}
