<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class UserSecurity extends Model
{
    use HasFactory;

    protected $table = 'user_securities';

    protected $fillable = [
        // Add your fillable fields here
    ];

    protected $casts = [
        // Add your casts here
    ];

    public function users(): BelongsToMany
    {
        return $this->belongsToMany(User::class, 'user_securities');
    }

    // Relationships generated by models:generate-relationships command
    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}
