<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UserProfile extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'title',
        'bio',
        'organization',
        'department',
        'position',
        'website',
        'social_links',
        'preferences',
    ];

    protected $casts = [
        'social_links' => 'array',
        'preferences' => 'array',
    ];

    // Relationships generated by models:generate-relationships command
    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}
